apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - args:
            - ./wait-for-it.sh
            - consul-agent:8500
            - --
            - dotnet
            - ApiGateway.dll
          env:
            - name: CONSUL_HTTP_ADDR
              value: http://consul-agent:8500
            - name: SERVICE_DISCOVERY_HOST
              value: consul-agent
            - name: SERVICE_DISCOVERY_PORT
              value: "8500"
          image: api-gateway
          name: api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 250m
              memory: "268435456"
      restartPolicy: Always
