apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 8080
  selector:
    io.kompose.service: api-gateway
