apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: bike-service
  name: bike-service
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: bike-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: bike-service
    spec:
      containers:
        - args:
            - ./wait-for-it.sh
            - -t
            - "60"
            - rabbitmq:5672
            - --
            - dotnet
            - BikeService.dll
          env:
            - name: CONSUL_HTTP_ADDR
              value: http://consul-agent:8500
            - name: EVENTSTORE_CONNECTION
              value: esdb://admin:changeit@eventstore:2113?tls=false
            - name: MONGODB_CONNECTION
              value: mongodb://root:rootpassword@mongodb:27017
          image: bike-service
          name: bike-service
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 250m
              memory: "268435456"
      restartPolicy: Always
