apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: bike-service
  name: bike-service
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 8080
  selector:
    io.kompose.service: bike-service
