apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: consul-agent
  name: consul-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: consul-agent
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: consul-agent
    spec:
      containers:
        - args:
            - consul
            - agent
            - -dev
            - -client=0.0.0.0
          image: hashicorp/consul:latest
          livenessProbe:
            exec:
              command:
                - consul
                - members
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: consul-agent
          ports:
            - containerPort: 8500
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 250m
              memory: "268435456"
      restartPolicy: Always
