apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: consul-agent
  name: consul-agent
spec:
  ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
  selector:
    io.kompose.service: consul-agent
