apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: eventstore
  name: eventstore
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: eventstore
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: eventstore
    spec:
      containers:
        - env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "1"
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: "true"
            - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
              value: "true"
            - name: EVENTSTORE_EXT_TCP_PORT
              value: "1113"
            - name: EVENTSTORE_HTTP_PORT
              value: "2113"
            - name: EVENTSTORE_INSECURE
              value: "true"
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: All
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: "true"
          image: eventstore/eventstore:21.10.1-buster-slim
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:2113/health/live
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: eventstore
          ports:
            - containerPort: 2113
              protocol: TCP
            - containerPort: 1113
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 250m
              memory: "268435456"
      restartPolicy: Always
