apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file ../docker-compose.yaml --replicas=3
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: eventstore
  name: eventstore
spec:
  ports:
    - name: "2113"
      port: 2113
      targetPort: 2113
    - name: "1113"
      port: 1113
      targetPort: 1113
  selector:
    io.kompose.service: eventstore
